controllers/TranslationController.php
<?php
/**
 * Created by PhpStorm.
 * User: Behzod
 * Date: 02.06.2019
 * Time: 21:04
 */

namespace app\controllers;

use app\models\Lang;
use app\models\Message;
use app\models\SourceMessage;
use Yii;
use yii\bootstrap\ActiveForm;
use yii\data\ActiveDataProvider;
use yii\helpers\Url;
use yii\web\Response;


class TranslationController extends Controller
{
    public function actionIndex()
    {
        $query = SourceMessage::find()->joinWith('messages')->orderBy(['id' => SORT_DESC]);
        if (isset($_GET['q'])) {
            $query->orFilterWhere(['like', "`message`.`translation`", $_GET['q']]);
            $query->orFilterWhere(['like', 'message', $_GET['q']]);
        }
        $data = new ActiveDataProvider([
            'query' => $query,
        ]);
        \Yii::$app->user->setReturnUrl(Url::to('/translation/index'));

        return $this->render('index', [
            'data' => $data
        ]);
    }

    public function actionCreate()
    {
        $model = new SourceMessage();

        if ($model->load(\Yii::$app->request->post())) {
            if (\Yii::$app->request->isAjax) {
                \Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            } else {
                if ($model->save()) {
                    Yii::$app->session->setflash('success', Yii::t('app', 'Message source is created'));
                    return $this->redirect(Url::to('/translation/index'));
                } else {
                    Yii::$app->session->setflash('error', Yii::t('app', 'Create error. {0}', $model->formatErrors()));
                    return $this->refresh();
                }
            }
        } else {
            return $this->render('create', [
                'model' => $model
            ]);
        }
    }

    public function actionEdit($id)
    {
        $model = SourceMessage::findOne($id);
        if ($model === null) {
            Yii::$app->session->setflash('error', \Yii::t('app', 'Not found'));
            return $this->redirect(Url::to('/translation/index'));
        }
        if ($model->load(\Yii::$app->request->post())) {
            if (\Yii::$app->request->isAjax) {
                \Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            } else {
                if ($model->save()) {
                    Yii::$app->session->setflash('success', Yii::t('app', 'Message is updated'));
                } else {
                    Yii::$app->session->setflash('error', Yii::t('app', 'Update error. {0}', $model->formatErrors()));
                }
                return $this->refresh();
            }
        } else {
            return $this->render('edit', [
                'model' => $model
            ]);
        }

    }
    public function actionSave()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        if (\Yii::$app->request->isAjax) {
            $post = Yii::$app->request->post()['data'];
            $temp = Message::find()->where(['language' => $post['language'], 'id' => $post['id']])->one();
            if ($temp) $model = $temp;
            else $model = new Message();
            $model->translation = $post['translation'];
            $model->language = $post['language'];
            if (!$temp) $model->id = $post['id'];
            if ($model->save()) {
                return ['status' => 'ok'];
            } else {
                return ['error' => $model->getErrors()];
            }
        }
    }
//    public function actionSave( $id)
//    {
//
//        $model = Message::find()->where(['id' => $id])->one();
//        if(!$model) $model = new Message();
//        if(Yii::$app->request->isPost){
//            if ($post = \Yii::$app->request->post() && $model->load(\Yii::$app->request->post())) {
//                if ($model->save()) {
//
//                    Yii::$app->session->setFlash('success',Yii::t( 'app','Message successfully saved!'));
//                    return $this->redirect('/translation/index');
//                } else {
//                    Yii::$app->session->setFlash('success', Yii::t('app','Something wentwrong'));
//
//                    return $this->render('add',[
//                        'model'=>$model,
//                        'id' => $id,
//                    ]);
//                }
//            }
//        }
//
//        return $this->render('add',[
//            'model'=>$model,
//            'id' => $id,
//        ]);
//    }
//
//    public function actionLanguage()
//    {
//        $data = new ActiveDataProvider([
//            'query' => Lang::find(),
//        ]);
//        \Yii::$app->user->setReturnUrl(Url::to('/translation/languages'));
//
//        return $this->render('language', [
//            'data' => $data
//        ]);
//    }

    public function actionLanguageedit($id)
    {
        $model = Lang::findOne(['id' => $id]);
        if ($model === null) {
            Yii::$app->session->setflash('error', \Yii::t('app', 'Not found'));
            return $this->redirect(Url::to('/translation/index'));
        }
        if ($model->load(\Yii::$app->request->post())) {
            if (\Yii::$app->request->isAjax) {
                \Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            } else {
                if ($model->save()) {
                    Yii::$app->session->setflash('success', \Yii::t('app', 'Language is updated'));
                } else {
                    Yii::$app->session->setflash('error', \Yii::t('app', 'Update error. {0}', $model->formatErrors()));
                }
                return $this->refresh();
            }
        } else {
            return $this->render('langedit', [
                'model' => $model
            ]);
        }
    }

    /**
     * @param $id
     * @return Response
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        if (($model = SourceMessage::findOne($id))) {
            $model->delete();
            Yii::$app->session->setFlash('success', Yii::t('app','Message successfully deleted!'));
        }
        return $this->redirect(['index']);
    }
}

views/translation/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>
<div class="content-box">
    <?php $form = ActiveForm::begin(['enableAjaxValidation' => true]); ?>
    <?= $form->field($model, 'category')->textInput(['value' => 'app']); ?>

    <?= $form->field($model, 'message')->textInput() ?>
    <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-primary btn-block']) ?>
    <?php ActiveForm::end(); ?>
</div>

views/translation/_form_lang.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>
<div class="panel panel-default">
    <div class="panel-heading">
        <?= Yii::t('app', 'Language management') ?>
    </div>
    <div class="panel-body">
        <div class="content-box">
            <?php $form = ActiveForm::begin(['enableAjaxValidation' => true]); ?>
            <?= $form->field($model, 'name')->textInput() ?>
            <?= $form->field($model, 'local')->textInput() ?>
            <?= $form->field($model, 'defaultl')->checkbox() ?>
            <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-primary btn-block']) ?>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/translation/_menu.php
<?php

use yii\helpers\Url;

$action = $this->context->action->id;
?>
<style>
    .list-group-horizontal .list-group-item {
        display: inline-block;
    }

    .list-group-horizontal .list-group-item {
        margin-bottom: 0;
        margin-left: -4px;
        margin-right: 0;
        border-right-width: 0;
    }

    .list-group-horizontal .list-group-item:first-child {
        border-top-right-radius: 0;
        border-bottom-left-radius: 4px;
    }

    .list-group-horizontal .list-group-item:last-child {
        border-top-right-radius: 4px;
        border-bottom-left-radius: 0;
        border-right-width: 1px;
    }
    .list-group-item.active > a, .list-group-item > a{
        color: white;
    }

</style>

<form class="form-inline">
    <ul class="list-group list-group-horizontal">
        <li class="list-group-item  bg-aqua <?= ($action === 'index') ? ' active ' : '' ?>">
            <a    href="<?= Url::to('/translation/index') ?>">
                <?= Yii::t('app', 'Translations') ?>
            </a>
        <li class="list-group-item bg-aqua">
            <a href="<?= Url::to('/translation/create') ?>">
                <?= Yii::t('app', 'Add word') ?></a>
        </li>

        <li class="list-group-item bg-aqua">
            <a href="<?= Url::to('/translation/language') ?>"><?= Yii::t('app', 'Languages') ?></a>
        </li>
    </ul>
</form>

views/translation/add.php
<?php

$languages = app\models\Lang::find()->all();
$this->title = Yii::t('app', 'Add translation');

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<div class="row">
    <div class="col s12">
        <div class="card">
            <div class="card-content">
                <?= \yii\bootstrap\Html::encode($this->title) ?>
            </div>
        </div>
    </div>

    <div class="col s12 m12 l12">
        <div class="card">
            <div class="card-content">

                <?php $form = ActiveForm::begin(); ?>
                <?= $form->field($model, 'language')->dropDownList(\yii\helpers\ArrayHelper::map(app\models\Lang::find()->all(),'url','name')) ?>

                <?= $form->field($model, 'id')->hiddenInput(['value'=> $id])->label(false) ?>
                <?= $form->field($model, 'translation')->textInput() ?>

                <div class="btn-group">
                    <button type="submit" class="btn-block waves-effect waves-light btn teal">
                        <?= Yii::t('app', "Save") ?>
                    </button>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>

views/translation/create.php
<?php
$this->title = Yii::t('app', 'Create template');
?>

<div class="col s12">
    <div class="card">
        <div class="card-content">
            <?= $this->render('_menu') ?>
        </div>
    </div>
</div>

<div class="col s12 m12 l12">
    <div class="card">
        <div class="card-content">
            <?= $this->render('_form', ['model' => $model]) ?>
        </div>
    </div>
</div>

views/translation/edit.php
<?php
$this->title = Yii::t('app', 'Edit page templates');
?>
<?= $this->render('_menu') ?>
<?= $this->render('_form', ['model' => $model]) ?>

views/translation/index.php
<?php
use app\models\Lang;
use yii\helpers\Html;
use yii\helpers\Url;
$languages=Lang::find()->all();
$this->title = Yii::t('app', 'Translations');
$this->registerJs("

$('.addTranslation').click(function(){
var pk=$(this).attr('data-pk');

var translation=$('#translation').val('');
$('#translationAdd').modal('show');
$('#pk').val(pk);
});
$('#saveTranslation').click(function(){
    var translation=$('#translation').val();
    var id=$('#pk').val();
    var language=$('#lang').val();
    $.post('/translation/save',{_csrf:'".Yii::$app->request->csrfToken."',data:{id:id,language:language,translation:translation}},function(){
        window.location.reload();
    });
});
$('.update-translation').click(function(){
    $('#lang').val($(this).attr('data-lang'));
    $('#translation').val($(this).attr('data-translation'));
    $('#pk').val($(this).attr('data-pk'));
    $('#translationAdd').modal('show');
});
");
?>
<div class="well well-sm">
    <?= $this->render('_menu') ?>
</div>
<!-- /.well -->
<div class="box">
    <div class="box-header">
        <!--            <h3 class="box-title">Responsive Hover Table</h3>-->

        <div class="box-tools">
            <form  >
                <div class="input-group input-group-sm hidden-xs" style="width: 150px;">
                    <input type="text" name="q" class="form-control" placeholder="<?= Yii::t('app', 'Search') ?>"/>

                    <div class="input-group-btn">
                        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                    </div>
                </div>

        </div>
    </div>
    <div class="box-body no-padding">
    <?php if($data->count > 0) : ?>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th width="50">#</th>
                <th><?= Yii::t('app', 'Name') ?></th>
                <th><?= Yii::t('app', 'Category') ?></th>
                <th><?= Yii::t('app', 'Default') ?></th>
                <th><?= Yii::t('app', 'Translations') ?></th>
                <th width="200"><?= Yii::t('app', 'Actions') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($data->models as $module) : ?>
                <tr>
                    <td><?= $module->primaryKey ?></td>
                    <td><a href="<?= \yii\helpers\Url::to('/translation/edit/'.$module->primaryKey) ?>" title="<?= Yii::t('app', 'Edit') ?>"><?= Yii::t("app",$module->message) ?></a></td>
                    <td><?= $module->getCatList()[$module->category] ?></td>
                    <td><?= $module->message?></td>
                    <td class="col-md-2">
                        <? if($module->messages)foreach ($module->messages as $message) {?>
                            <button type="button" class="btn btn-success btn-sm update-translation"
                                    data-pk="<?=$message->id?>"
                                    data-lang="<?=$message->language?>"
                                    data-translation="<?=$message->translation?>">
                                <?=$message->language?>
                            </button>
                        <?}?>
                    </td>
                    <td class="control">
                        <div class="btn-group btn-group-sm" role="group">
                            <a href="<?= \yii\helpers\Url::to('/translation/edit/'. $module->primaryKey) ?>" class="btn btn-success" title="<?= Yii::t('app', 'Move up') ?>"><span class="fa fa-edit"></span></a>
                            <a data-pk="<?=$module->primaryKey?>"
                               class="btn btn-info addTranslation"
                               title="<?= Yii::t('app', 'Add translation') ?>">
                                <span class="fa fa-plus"></span>
                            </a>
                            <a href="<?= \yii\helpers\Url::to('/translation/delete/'.$module->primaryKey) ?>" class="btn btn-danger confirm-delete" title="<?= Yii::t('app', 'Delete item') ?>"><span class="fa fa-times"></span></a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
            <tfoot>
            <tr>
                <td colspan="5">
                    <?= yii\widgets\LinkPager::widget([
                        'pagination' => $data->pagination
                    ]) ?>
                </td>
            </tr>
            </tfoot>

        </table>
    <?php else : ?>
        <p><?= Yii::t('app', 'No records found') ?></p>
    <?php endif; ?>
</div>
<div id="translationAdd" class="modal fade"  role="dialog" aria-hidden="true">
    <div class="modal-dialog" >
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?=Yii::t('app','Add new translation')?></h4>
            </div>
            <form  autocomplete='off'>
                <div class="modal-body">

                    <input type="hidden" id="pk"/>
                    <div class="form-group">
                        <select class="form-control" id="lang" autocomplete='false' >
                            <option selected hidden>Русский</option>
                            <? foreach ($languages as $language) {?>
                                <option value="<?=$language->url?>" <?if($language->url=='ru'){?>selected<?}?>><?=$language->name?> </option>
                            <?}?>
                        </select>
                    </div>
                    <div class="form-group">
                        <input name="translation" type="text" id="translation" class="form-control" placeholder="<?=Yii::t('app',"Translation")?>"/>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?=Yii::t('app','Close')?></button>
                    <button type="button" class="btn btn-primary" id="saveTranslation"><?=Yii::t('app','Save')?></button>
                </div>
            </form>
        </div>
    </div>
</div>

views/translation/langedit.php
<?php
$this->title = Yii::t('app', 'Edit language');
?>
<?= $this->render('_menu') ?>
<?= $this->render('_form_lang', ['model' => $model]) ?>

views/translation/language.php
<?php

use yii\helpers\Url;

$this->title = Yii::t('app', 'Languages');
?>
<?= $this->render('_menu') ?>
<div class="content-box">
    <?php if ($data->count > 0) : ?>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th width="50">#</th>
                <th><?= Yii::t('app', 'Name') ?></th>
                <th><?= Yii::t('app', 'Title') ?></th>
                <th><?= Yii::t('app', 'Translations') ?></th>
                <th width="200"><?= Yii::t('app', 'Change') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php $number = 1;
            foreach ($data->models as $module) : ?>
                <tr>
                    <td><?= $number++; ?></td>
                    <td><a href="<?= Url::to('/translation/edit/' . $module->primaryKey) ?>"
                           title="<?= Yii::t('app', 'Edit') ?>"><?= $module->name ?></a></td>
                    <td><?= $module->url ?></td>
                    <td><?= $module->name ?></td>
                    <td class="control">
                        <div class="btn-group btn-group-sm" role="group">
                            <a href="<?= Url::to('/translation/languageedit/' . $module->primaryKey) ?>"
                               class="btn btn-success" title="<?= Yii::t('app', 'Move up') ?>"><span
                                        class="fa fa-edit"></span></a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
            <? try {
                echo yii\widgets\LinkPager::widget([
                    'pagination' => $data->pagination
                ]);
            } catch (Exception $e) {
            } ?>
        </table>
    <?php else : ?>
        <p><?= Yii::t('app', 'No records found') ?></p>
    <?php endif; ?>
</div>