models/User.php
<?php

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string $login
 * @property string $email
 * @property int $user_group
 * @property int $role
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $auth_key
 * @property int $status
 * @property string $lastname
 * @property string $firstname
 * @property string $middlename
 * @property int $created_at
 * @property int $updated_at
 */

class User extends ActiveRecord implements IdentityInterface
{
    const USER_ACTIVE = 1;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_group', 'role', 'status', 'created_at', 'updated_at'], 'integer'],
            [['password_hash', 'password_reset_token', 'auth_key'], 'string'],
            [['login', 'lastname', 'firstname', 'middlename'], 'string', 'max' => 50],
            [['email'], 'string', 'max' => 70],
            [['login'], 'unique']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'login' => Yii::t('app', 'Login'),
            'email' => Yii::t('app', 'Email'),
            'user_group' => Yii::t('app', 'User Group'),
            'role' => Yii::t('app', 'Role'),
            'password_hash' => Yii::t('app', 'Password Hash'),
            'password_reset_token' => Yii::t('app', 'Password Reset Token'),
            'auth_key' => Yii::t('app', 'Auth Key'),
            'status' => Yii::t('app', 'Status'),
            'lastname' => Yii::t('app', 'Lastname'),
            'firstname' => Yii::t('app', 'Firstname'),
            'middlename' => Yii::t('app', 'Middlename'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @return array
     */
    public static function dropDownList()
    {
        return ArrayHelper::map(self::findAll(['status' => User::USER_ACTIVE]), 'id', 'fullname');
    }

    /**
     * @param int|string $id
     * @return User|null|IdentityInterface
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id]);
    }

    /**
     * @param mixed $token
     * @param null $type
     * @return void|IdentityInterface
     * @throws NotSupportedException
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return User|null|string
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @param string $authKey
     * @return User|bool|null
     */
    public function validateAuthKey($authKey)
    {
        return $this->auth_key == $authKey;
    }

    /**
     * @param $password
     * @return bool
     */
    public function validatePassword($password)
    {
        return Yii::$app->getSecurity()->validatePassword($password, $this->password_hash);
    }

    /**
     * @throws \yii\base\Exception
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * @return string
     * @throws \yii\base\Exception
     */
    public function generateToken()
    {
        return $this->accessToken = Yii::$app->security->generateRandomString();
    }

    /**
     * @param $password
     * @throws \yii\base\Exception
     */
    public function setPassword($password)
    {
        $this->password = Yii::$app->getSecurity()->generatePasswordHash($password);
    }

    public static function hasRole($roleName, $userId)
    {
        $authManager = \Yii::$app->getAuthManager();
        return $authManager->getAssignment($roleName, $userId) ? true : false;
    }

    public static function usersByRole($roleName)
    {
        $authManager = \Yii::$app->getAuthManager();
        return $authManager->getUserIdsByRole($roleName);
    }

    public static function canUpdate($owner)
    {
        return ($owner === Yii::$app->user->identity->id || User::hasRole('ADMINISTRATOR', Yii::$app->user->identity->id)) ? true : false;
    }

    public function getFio(){
        $ret = $this->lastname." ".substr($this->firstname, 0, 1).".".substr($this->middlename, 0, 1).".";
        if(strlen($ret)<6){
            return $this->login;
        }else{
            return $ret;
        }
    }

}

views/blocks/footer.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>GEMINI TEST</b> v1.0
    </div>

</footer>

views/blocks/header.php
<?php
use yii\helpers\Url;
echo \app\widgets\Toastr::widget();
?>
<header class="main-header">

    <!-- Logo -->
    <a href="<?=Url::to('/')?>" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b style="color: #f39c12">G-T</b></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b style="color: #f39c12">G-T</b>EST</span>
    </a>

    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="/web/css/dist/img/default-photo.png" class="img-circle" style="height: 18px" alt="User Image">
                        <span class="hidden-xs"><?=$user->fio?></span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="/web/css/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">

                            <p>
                                <?=$user->login?> - Web Developer
                                <small>Member since Nov. 2012</small>
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="<?=Url::to('/profile')?>" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="<?=Url::to('/sign/out')?>" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>

            </ul>
        </div>

    </nav>
</header>

views/blocks/left.php
<?php
/**
 * Created by PhpStorm.
 * User: Behzod
 * Date: 07.07.2019
 * Time: 17:19
 * @var $controller Yii::$app->controller->id
 * @var $action Yii::$app->controller->action->id
 * @var $user  Yii::$app->user->identity
 */

use yii\helpers\Url;
$checkUser = Yii::$app->user;
?>


<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="/web/css/dist/img/default-photo.png" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p><?= $user->fio ?></p>
                <a><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                      <i class="fa fa-search"></i>
                    </button>
                  </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header"><?= Yii::t('app', 'MAIN NAVIGATION') ?></li>
            <? if ($checkUser->can("DASHBOARD")) { ?>
                <li class="<?= ($controller == 'site' && $action == 'index') ? 'active' : "" ?>">
                    <a href="<?= Url::to('/') ?>">
                        <i class="fa fa-home"></i> <span><?= Yii::t('app', 'Dashboard') ?></span>
                    </a>
                </li>
            <? } ?>
            <? if ($checkUser->can("Journal-index")) { ?>
                <li class="<?= ($controller == 'site' && $action == 'index') ? 'active' : "" ?>">
                    <a href="<?= Url::to('/journal/index') ?>">
                        <i class="fa fa-file-text-o"></i> <span><?= Yii::t('app', 'Journal') ?></span>
                    </a>
                </li>
            <? } ?>
            <? if ($checkUser->can("Test-all")) { ?>
                <li class="<?= ($controller == 'site' && $action == 'index') ? 'active' : "" ?>">
                    <a href="<?= Url::to('/test/all') ?>">
                        <i class="fa  fa-tasks"></i> <span><?= Yii::t('app', 'All tests') ?></span>
                    </a>
                </li>
            <? } ?>
            <? if ($checkUser->can("Test-pass")) { ?>
                <li class="<?= ($controller == 'site' && $action == 'index') ? 'active' : "" ?>">
                    <a href="<?= Url::to('/test/pass') ?>">
                        <i class="fa  fa-tasks"></i> <span><?= Yii::t('app', 'Pass the test') ?></span>
                    </a>
                </li>
            <? } ?>
            <? if ($checkUser->can("Test-create")) { ?>
                <li class="<?= ($controller == 'site' && $action == 'index') ? 'active' : "" ?>">
                    <a href="<?= Url::to('/test/create') ?>">
                        <i class="fa  fa-tasks"></i> <span><?= Yii::t('app', 'Create test') ?></span>
                    </a>
                </li>
            <? } ?>
            <? if ($checkUser->can("Configurations-index")) { ?>
                <li class="<?= ($controller == 'configurations' && $action == 'index') ? 'active' : "" ?>">
                    <a href="<?= Url::to('/configurations/index') ?>">
                        <i class="fa  fa-tasks"></i> <span><?= Yii::t('app', 'Configurations') ?></span>
                    </a>
                </li>
            <? } ?>
            <? if ($checkUser->can("Category-index")) { ?>
                <li class="<?= ($controller == 'category') ? 'active' : "" ?>">
                    <a href="<?= Url::to('/category/index') ?>">
                        <i class="fa fa-truck" style="position:relative; color: #000;">
                            <i style="position: absolute; right: 3px; bottom: 0; color: #f39c12; font-size: 65%"
                               class="fa fa-car"></i>
                        </i>
                        <span><?= Yii::t('app', 'Categories') ?></span>
                    </a>
                </li>
            <? } ?>
            <? if ($checkUser->can("Subject-index")) { ?>
                <li class="<?= ($controller == 'subject') ? 'active' : "" ?>">
                    <a href="<?= Url::to('/subject/index') ?>">
                        <i class="fa fa-book" style="position:relative; color: #000;"></i>
                        <span><?= Yii::t('app', 'Subjects') ?></span>
                    </a>
                </li>
            <? } ?>
            <? if ($checkUser->can("UserGroup-index")) { ?>
                <li class="<?= ($controller == 'user-group') ? 'active' : "" ?>">
                    <a href="<?= Url::to('/user-group/index') ?>">
                        <i class="fa fa-group"></i>
                        <span><?= Yii::t('app', 'Groups') ?></span>
                    </a>
                </li>
            <? } ?>
            <? if ($checkUser->can("User-index")) { ?>
                <li class="<?= ($controller == 'user' && $action == 'about') ? 'active' : "" ?>">
                    <a href="<?= Url::to('/user/index') ?>">
                        <i class="fa fa-user"></i>
                        <span><?= Yii::t('app', 'Users') ?></span>
                    </a>
                </li>
            <? } ?>
            <? if ($checkUser->can("DEVELOPER")) { ?>
                <li class="<?= ($controller == 'icons' && $action == 'contact') ? 'active' : "" ?>">
                    <a href="<?= Url::to('/site/icons') ?>">
                        <i class="fa fa-circle-o text-yellow"></i>
                        <span><?= Yii::t('app', 'Icons') ?></span>
                    </a>
                </li>
            <? } ?>
            <? if ($checkUser->can("Auth-index")) { ?>
                <li class="<?= ($controller == 'icons' && $action == 'contact') ? 'active' : "" ?>">
                    <a href="<?= Url::to('/auth/default/index') ?>">
                        <i class="fa fa-circle-o text-yellow"></i>
                        <span><?= Yii::t('app', 'Auth') ?></span>
                    </a>
                </li>
            <? } ?>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

views/blocks/loader.php
preloader