models/UserGroup.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "user_group".
 *
 * @property int $id
 * @property string $title
 * @property int $category_id
 * @property GroupSubject[] $subject_id
 * @property int $user_id
 * @property int $created_at
 * @property int $updated_at
 *
 * @property Category $category
 * @property Subject[] $subjectGroup
 */
class UserGroup extends \yii\db\ActiveRecord
{
    public $subject_id;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user_group';
    }

    public static function dropList()
    {
        return ArrayHelper::map(self::find()->all(), 'id', 'title');
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'category_id', 'subject_id'], 'required'],
            [['category_id', 'user_id'], 'integer'],
            [['title', 'created_at', 'updated_at'], 'string', 'max' => 255],
            [['subject_id'], 'safe'],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(), 'targetAttribute' => ['category_id' => 'id']],
        ];
    }

    public function beforeSave($insert)
    {
        if ($insert){
            $this->user_id = Yii::$app->user->identity->id;
        }
        if(is_string($this->updated_at))$this->updated_at = strtotime($this->updated_at);
        if(is_string($this->created_at))$this->created_at = strtotime($this->created_at);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


    public function afterFind()
    {
        $this->created_at = date('d.m.Y', $this->created_at);
        $this->updated_at = date('d.m.Y', $this->updated_at);
        $this->subject_id = ArrayHelper::map(GroupSubject::find()->select(['s_id'])->all(), 's_id', 's_id');
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'title' => Yii::t('app', 'Title'),
            'category_id' => Yii::t('app', 'Category'),
            'subject_id' => Yii::t('app', 'Subject'),
            'user_id' => Yii::t('app', 'User'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }
    public function getSubjectGroup()
    {
        return $this->hasMany(GroupSubject::className(), ['g_id' => 'id']);
    }
    public function getSubjectString(){
        $ret = '';
        foreach ($this->subjectGroup as $s){
            $ret .= $s->subject->title.", ";
        }
        return $ret;
    }
}

controllers/UserGroupController.php
<?php

namespace app\controllers;

use app\models\GroupSubject;
use app\models\Subject;
use Codeception\Platform\Group;
use Yii;
use app\models\UserGroup;
use app\models\UserGroupSearch;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserGroupController implements the CRUD actions for UserGroup model.
 */
class UserGroupController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all UserGroup models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserGroupSearch();
        $dataProvider = $searchModel->search(['UserGroupSearch'=>Yii::$app->request->queryParams]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Creates a new UserGroup model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new UserGroup();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if(is_array($model->subject_id)){
                foreach ($model->subject_id as $s){
                    $gs = new GroupSubject();
                    $gs->g_id = $model->id;
                    $gs->s_id = $s;
                    if(!$gs->save()){
                        Yii::$app->session->addFlash('danger', Yii::t('app', 'Error in save Group Subject Relation'));
                    }
                }
            }

            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing UserGroup model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if(is_array($model->subject_id)){

                GroupSubject::deleteAll(['g_id'=>$model->id]);
                foreach ($model->subject_id as $s){
                    $gs = new GroupSubject();
                    $gs->g_id = $model->id;
                    $gs->s_id = $s;
                    if(!$gs->save()){
                        Yii::$app->session->addFlash('danger', Yii::t('app', 'Error in save Group Subject Relation'));
                    }
                }
            }
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing UserGroup model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the UserGroup model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return UserGroup the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = UserGroup::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }

    public function actionSubjectByCategory($id){
        return json_encode(Subject::find()->select(['id as id', 'title as title'])->where(['category_id'=>$id])->asArray()->all(), JSON_UNESCAPED_UNICODE);
    }
}

views/user-group/create.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserGroup */

$this->title = Yii::t('app', 'Create User Group');
$this->params['breadcrumbs'][] = Yii::t('app', 'User Groups');
$this->params['breadcrumbs'][] = $this->title;


?>
<div class="user-group-create">

    <div class="row">
        <div class="col-md-12">
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
                </div>
                <?php $form = ActiveForm::begin(); ?>
                <div class="box-body">
                    <?= $form->field($model, 'title',['template'=>'<div class="form-group">{label}{input}<div class="col-md-12">{error}</div></div>'])->textInput(['maxlength' => true]) ?>
                </div>
                <div class="box-body">
                    <?$categoryList = \app\models\Category::dropList();?>
                    <?= $form->field($model, 'category_id',['template'=>'<div class="form-group">{label}{input}<div class="col-md-12">{error}</div></div>'])->dropDownList($categoryList,['class'=>'form-control select2 auto-complete-select', 'data-child'=>'usergroup-subject_id', 'data-url'=>Url::to('/user-group/subject-by-category')]) ?>
                </div>
                <div class="box-body">
                    <?= $form->field($model, 'subject_id',['template'=>'<div class="form-group">{label}{input}<div class="col-md-12">{error}</div></div>'])->dropDownList(\app\models\Subject::dropListByCategory(array_key_first($categoryList)),['class'=>'form-control select2', 'multiple'=>true]) ?>
                </div>
                <div class="box-footer">
                    <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>

</div>

views/user-group/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UserGroupSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'User Groups');
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="user-group-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(); ?>

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"><?= Html::a(Yii::t('app', 'Create Group'), ['create'], ['class' => 'btn btn-block btn-success btn-flat']) ?></h3>

                    <div class="box-tools">
                        <?$form = \yii\widgets\ActiveForm::begin(['action'=>'/user-group/index','method'=>'get'])?>
                        <div class="input-group input-group-sm hidden-xs" style="width: 150px;">
                            <input type="text" name="title" class="form-control pull-right" value="<?=$searchModel->title?>" placeholder="<?=Yii::t('app','Search')?>">
                            <div class="input-group-btn"><button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button></div>
                        </div>
                        <? \yii\widgets\ActiveForm::end()?>
                    </div>

                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <tbody>
                        <tr>
                            <th>№</th>
                            <th><?=$searchModel->getAttributeLabel('title')?></th>
                            <th><?=$searchModel->getAttributeLabel('category_id')?></th>
                            <th><?=$searchModel->getAttributeLabel('subject_id')?></th>
                            <th><?=$searchModel->getAttributeLabel('updated_at')?></th>
                            <th><?=$searchModel->getAttributeLabel('created_at')?></th>
                            <th></th>
                        </tr>
                        <?$i = 1;?>
                        <? foreach ($dataProvider->models as $model):
                            /**
                             * @var $model \app\models\Category
                             */
                            ?>
                            <tr>
                                <td><?=$i++?></td>
                                <td><?=$model->title?></td>
                                <td><?=$model->category->title?></td>
                                <td><?=$model->subjectString?></td>
                                <td><?=$model->updated_at?></td>
                                <td><?=$model->created_at?></td>
                                <td width="100px">
                                    <div class="btn-group">
                                        <a class="btn btn-warning" href="<?=\yii\helpers\Url::to(['/user-group/update','id'=>$model->id])?>"><i class="fa fa-edit"></i></a>
                                        <a class="btn btn-danger" data-confirm="<?=Yii::t('app', 'Are you sure you want to delete this item?')?>" data-method="post" href="<?=\yii\helpers\Url::to('/user-group/delete/'.$model->id)?>"><i class="fa fa-trash"></i></a>
                                    </div>

                                </td>
                            </tr>
                        <?endforeach;?>
                        <?if(count($dataProvider->models)<1):?>
                            <tr>
                                <td colspan="5">
                                    <?=Yii::t('app','Data not found')?>
                                </td>
                            </tr>
                        <?endif;?>
                        </tbody>
                    </table>
                    <div class="box-footer clearfix">
                        <?=\yii\widgets\LinkPager::widget(['pagination' => $dataProvider->pagination,'options'=>['class'=>'pagination pagination-sm no-margin pull-right'],'activePageCssClass' => 'green-active',])?>
                    </div>

                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
    <?php Pjax::end(); ?>
</div>

views/user-group/update.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\UserGroup */

$this->title = Yii::t('app', 'Update User Group: {name}', [
    'name' => $model->title,
]);
$this->params['breadcrumbs'][] = Yii::t('app', 'User Groups');
$this->params['breadcrumbs'][] = $model->title;
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');


$this->registerCssFile('/web/css/bower_components/select2/dist/css/select2.min.css');
$this->registerJsFile('/web/css/bower_components/select2/dist/js/select2.full.min.js', ['depends'=>'app\asset\AppAsset']);

?>
<div class="user-group-update">

    <div class="row">
        <div class="col-md-12">
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
                </div>
                <?php $form = ActiveForm::begin(); ?>
                <div class="box-body">
                    <?= $form->field($model, 'title',['template'=>'<div class="form-group">{label}{input}<div class="col-md-12">{error}</div></div>'])->textInput(['maxlength' => true]) ?>
                </div>
                <div class="box-body">
                    <?$categoryList = \app\models\Category::dropList();?>
                    <?= $form->field($model, 'category_id',['template'=>'<div class="form-group">{label}{input}<div class="col-md-12">{error}</div></div>'])->dropDownList($categoryList,['class'=>'form-control select2 auto-complete-select', 'data-child'=>'usergroup-subject_id', 'data-url'=>Url::to('/user-group/subject-by-category')]) ?>
                </div>
                <div class="box-body">
                    <?= $form->field($model, 'subject_id',['template'=>'<div class="form-group">{label}{input}<div class="col-md-12">{error}</div></div>'])->dropDownList(\app\models\Subject::dropListByCategory(array_key_first($categoryList)),['class'=>'form-control select2', 'multiple'=>true]) ?>
                </div>
                <div class="box-footer">
                    <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>

</div>